server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info

spring:
  thymeleaf:
    cache: false

#security:
#  oauth2:
#    resource:
##      user-info-uri: http://localhost:8080/userInfo
##      prefer-token-info: false
#      filter-order: 99
