server:
  port: 8761
security:
  basic:
    enabled: false
#eureka:
#  server:
#    eviction-interval-timer-in-ms: 5000             # 续期时间，即扫描失效服务的间隔时间 (缺省为60*1000ms)
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5            # 心跳时间，即服务续约间隔时间 (缺省为30s)
#    lease-expiration-duration-in-seconds: 15        # 发呆时间，即服务续约到期时间 (缺省为90s)
  client:
    register-with-eureka: false
    fetch-registry: false
#    registry-fetch-interval-seconds: 6              # 拉取地址时间, 即间隔多长时间到服务端拉取最新的服务实例地址 (缺省为30s)
#    eureka-service-url-poll-interval-seconds: 60    # 拉取服务变更时间, 即客户端多长时间拉取服务端状态判定是否新增移除服务端 (缺省为300s)
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
